import type { ItemDetail } from "@/types/products"

const EMPTY_CHANNEL = {
  name: null, code: null, barcode: null, quantity: null, price: null,
  sellStatus: null, releasedAt: null, discontinuedAt: null, discontinuedReason: null,
} as const

const EMPTY_PROCESS = {
  preprocessTotalWeight: null, preprocessLossWeight: null,
  coolingTotalWeight: null, coolingLossWeight: null, coolingTimeSeconds: null,
  packagingTotalWeight: null, packagingLossWeight: null,
  laborTime: null, expenseWeight: null,
  standardMaterialCost: null, standardLaborCost: null, standardExpenseCost: null,
  weightSorterNo2f: null, weightSorterNo3f: null,
} as const

const EMPTY_QUALITY = {
  reportNumber: null, reportDate: null, reportFileId: null,
  foodType: null, sterilizationType: null, expirationPeriod: null,
  labeling: null, allergyLabeling: null, labelingForProduct: null,
  dominoFileId: null, dominoImageId: null, calorie: null,
  storageInstruction: null, isHaccp: null,
  mainIngredient: null, mainIngredientRate: null, allergyIngredients: null,
  manufacturer: null, manufacturerAddress: null,
  repacker: null, repackerAddress: null,
  supplier: null, supplierAddress: null,
  returnAddress: null, customerServiceTel: null,
  packagingMaterial: null, commonLabeling: null,
} as const

export const mockItemDetails: ItemDetail[] = [
  {
    code: "P-001",
    name: "닭갈비",
    category: "반찬",
    unit: "EA",
    weightPerUnit: "200g",
    storageMethod: "REFRIGERATED",
    type: "FINISHED_PRODUCT",
    purchasePrice: 1800,
    purchaseVat: 10,
    salePrice: 3500,
    saleVat: 10,
    companyId: "식자재㈜",
    moq: null,
    stockControl: "Y",
    safetyStockQty: null,
    leadTimeDays: null,
    note: null,
    productBarcode: null,
    outerBoxBarcode: null,
    unitsPerBox: null,
    isSet: "N",
    isActive: "Y",
    deactivationReason: null,
    processInfo: { ...EMPTY_PROCESS, packagingTotalWeight: 200, laborTime: 5 },
    quality: { ...EMPTY_QUALITY, foodType: "즉석조리식품", expirationPeriod: "7일", storageInstruction: "냉장보관(0~10℃)" },
    salesChannels: {
      store: { name: "닭갈비 200g", code: "S-P-001", barcode: "8801234567890", quantity: 1, price: 3500, sellStatus: "SELLING", releasedAt: "2026-01-01", discontinuedAt: null, discontinuedReason: null },
      coupang: { ...EMPTY_CHANNEL },
      kurly: { ...EMPTY_CHANNEL },
    },
  },
  {
    code: "P-002",
    name: "제육볶음",
    category: "반찬",
    unit: "EA",
    weightPerUnit: "200g",
    storageMethod: "REFRIGERATED",
    type: "FINISHED_PRODUCT",
    purchasePrice: 2200,
    purchaseVat: 10,
    salePrice: 4200,
    saleVat: 10,
    companyId: "식자재㈜",
    moq: null,
    stockControl: "Y",
    safetyStockQty: null,
    leadTimeDays: null,
    note: null,
    productBarcode: null,
    outerBoxBarcode: null,
    unitsPerBox: null,
    isSet: "N",
    isActive: "Y",
    deactivationReason: null,
    processInfo: { ...EMPTY_PROCESS },
    quality: { ...EMPTY_QUALITY, foodType: "즉석조리식품", expirationPeriod: "7일" },
    salesChannels: {
      store: { ...EMPTY_CHANNEL },
      coupang: { ...EMPTY_CHANNEL },
      kurly: { ...EMPTY_CHANNEL },
    },
  },
  {
    code: "P-003",
    name: "시금치나물",
    category: "나물",
    unit: "EA",
    weightPerUnit: "150g",
    storageMethod: "REFRIGERATED",
    type: "FINISHED_PRODUCT",
    purchasePrice: 800,
    purchaseVat: 10,
    salePrice: 2000,
    saleVat: 10,
    companyId: "채소농원",
    moq: null,
    stockControl: "Y",
    safetyStockQty: null,
    leadTimeDays: null,
    note: null,
    productBarcode: null,
    outerBoxBarcode: null,
    unitsPerBox: null,
    isSet: "N",
    isActive: "Y",
    deactivationReason: null,
    processInfo: { ...EMPTY_PROCESS },
    quality: { ...EMPTY_QUALITY },
    salesChannels: {
      store: { ...EMPTY_CHANNEL },
      coupang: { ...EMPTY_CHANNEL },
      kurly: { ...EMPTY_CHANNEL },
    },
  },
  {
    code: "P-004",
    name: "콩자반",
    category: "콩류",
    unit: "EA",
    weightPerUnit: "150g",
    storageMethod: "REFRIGERATED",
    type: "FINISHED_PRODUCT",
    purchasePrice: 1200,
    purchaseVat: 10,
    salePrice: 2500,
    saleVat: 10,
    companyId: "두부농원",
    moq: null,
    stockControl: "Y",
    safetyStockQty: null,
    leadTimeDays: null,
    note: null,
    productBarcode: null,
    outerBoxBarcode: null,
    unitsPerBox: null,
    isSet: "N",
    isActive: "Y",
    deactivationReason: null,
    processInfo: { ...EMPTY_PROCESS },
    quality: { ...EMPTY_QUALITY },
    salesChannels: {
      store: { ...EMPTY_CHANNEL },
      coupang: { ...EMPTY_CHANNEL },
      kurly: { ...EMPTY_CHANNEL },
    },
  },
  {
    code: "P-005",
    name: "잡채",
    category: "반찬",
    unit: "EA",
    weightPerUnit: "250g",
    storageMethod: "REFRIGERATED",
    type: "FINISHED_PRODUCT",
    purchasePrice: 2500,
    purchaseVat: 10,
    salePrice: 4800,
    saleVat: 10,
    companyId: "식자재㈜",
    moq: null,
    stockControl: "Y",
    safetyStockQty: null,
    leadTimeDays: null,
    note: null,
    productBarcode: null,
    outerBoxBarcode: null,
    unitsPerBox: null,
    isSet: "N",
    isActive: "N",
    deactivationReason: "단종",
    processInfo: { ...EMPTY_PROCESS },
    quality: { ...EMPTY_QUALITY },
    salesChannels: {
      store: { ...EMPTY_CHANNEL },
      coupang: { ...EMPTY_CHANNEL },
      kurly: { ...EMPTY_CHANNEL },
    },
  },
]
