"use client";

import { useRouter } from "next/navigation";
import { mockKanbans } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { ArrowRight, ArrowLeft, Printer, Wand2, Trash2 } from "lucide-react";
import { useState } from "react";

type Status = "대기" | "진행" | "완료";
type Kanban = Omit<typeof mockKanbans[0], "status" | "startTime" | "endTime"> & { status: Status; startTime: string | null; endTime: string | null; printed: boolean };

export default function KanbanPage() {
  const router = useRouter();
  const [kanbans, setKanbans] = useState<Kanban[]>(
    mockKanbans.map((k) => ({ ...k, printed: false }))
  );
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [selected, setSelected] = useState<Kanban | null>(null);
  const [newStatus, setNewStatus] = useState<Status>("대기");

  const printAll = () => setKanbans((prev) => prev.map((k) => ({ ...k, printed: true })));

  const handleAutoGenerate = () => {
    setKanbans(prev => [
      ...prev,
      {
        id: "A-20260602-003", team: "1반", product: "닭갈비", qty: 100, unit: "팩",
        process: "포장", status: "대기" as const, assignee: "김철수",
        startTime: null, endTime: null, progress: 0, printed: false,
      },
    ]);
    setAutoGenerated(true);
  };

  const openStatusDialog = (k: Kanban) => {
    setSelected(k);
    setNewStatus(k.status as Status);
  };

  const saveStatus = () => {
    if (!selected) return;
    setKanbans(prev => prev.map(k => {
      if (k.id !== selected.id) return k;
      const progress = newStatus === "완료" ? 100 : newStatus === "진행" ? 50 : 0;
      return { ...k, status: newStatus as Status, progress };
    }));
    setSelected(null);
  };

  return (
    <div className="p-6 space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-2 text-xs text-gray-500 mb-1">
            <span className="text-gray-400">생산계획 PULL</span>
            <span>›</span>
            <span className="text-blue-600 font-medium">3단계: 간반</span>
          </div>
          <h1 className="text-xl font-bold text-gray-900">간반</h1>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={() => router.push("/production/expansion")}>
            <ArrowLeft className="w-3.5 h-3.5 mr-1" /> 전개
          </Button>
          <Button variant="outline" size="sm" className="gap-1.5" onClick={handleAutoGenerate} disabled={autoGenerated}>
            <Wand2 className="w-3.5 h-3.5" />
            {autoGenerated ? "자동 생성 완료" : "자동 생성"}
          </Button>
          <Button variant="outline" size="sm" className="gap-1.5" onClick={printAll}>
            <Printer className="w-3.5 h-3.5" />
            전체 출력
          </Button>
          <Button size="sm" className="gap-1.5" onClick={() => router.push("/production/execute")}>
            생산으로 이동
            <ArrowRight className="w-3.5 h-3.5" />
          </Button>
        </div>
      </div>

      {autoGenerated && (
        <div className="text-xs text-green-600 bg-green-50 border border-green-200 rounded px-3 py-2">
          자동 생성 완료 — A-20260602-003 (닭갈비 포장) 추가되었습니다.
        </div>
      )}

      <Card>
        <CardContent className="p-0">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-gray-50">
                {["간반번호", "반 구분", "제품명", "수량", "단위", "담당 공정", "상태", "출력", "", ""].map((h, hi) => (
                  <th key={`${h}-${hi}`} className="px-4 py-2.5 text-left text-xs font-medium text-gray-500">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y">
              {kanbans.map((k, i) => (
                <tr key={k.id} className="hover:bg-gray-50 cursor-pointer" onClick={() => openStatusDialog(k)}>
                  <td className="px-4 py-3 font-mono text-xs font-medium text-gray-800">{k.id}</td>
                  <td className="px-4 py-3 text-xs text-gray-600">{k.team}</td>
                  <td className="px-4 py-3 font-medium text-gray-900">{k.product}</td>
                  <td className="px-4 py-3 text-right font-medium">{k.qty}</td>
                  <td className="px-4 py-3 text-xs text-gray-500">{k.unit}</td>
                  <td className="px-4 py-3 text-xs text-gray-600">{k.process}</td>
                  <td className="px-4 py-3">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium cursor-pointer ${
                      k.status === "완료" ? "bg-green-100 text-green-700" :
                      k.status === "진행" ? "bg-blue-100 text-blue-700" :
                      "bg-gray-100 text-gray-500"
                    }`}>{k.status}</span>
                  </td>
                  <td className="px-4 py-3">
                    <span className={`text-xs px-2 py-0.5 rounded-full ${kanbans[i].printed ? "bg-green-100 text-green-600" : "bg-gray-100 text-gray-400"}`}>
                      {kanbans[i].printed ? "출력완료" : "미출력"}
                    </span>
                  </td>
                  <td className="px-4 py-3" onClick={e => e.stopPropagation()}>
                    <Button
                      variant="ghost"
                      size="sm"
                      className="h-6 text-xs"
                      onClick={() => setKanbans((prev) => prev.map((item, idx) => idx === i ? { ...item, printed: true } : item))}
                    >
                      <Printer className="w-3 h-3 mr-1" />
                      출력
                    </Button>
                  </td>
                  <td className="px-4 py-3" onClick={e => e.stopPropagation()}>
                    {!k.printed && (
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 text-xs text-red-500 hover:text-red-700 hover:bg-red-50"
                        onClick={() => setKanbans((prev) => prev.filter((_, idx) => idx !== i))}
                      >
                        <Trash2 className="w-3 h-3 mr-1" />
                        삭제
                      </Button>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </CardContent>
      </Card>

      <Dialog open={!!selected} onOpenChange={o => !o && setSelected(null)}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>간반 상태 변경 — {selected?.id}</DialogTitle>
          </DialogHeader>
          {selected && (
            <div className="space-y-3 mt-2">
              <div className="grid grid-cols-2 gap-3 text-sm">
                <div><span className="text-xs text-gray-500">제품명</span><div className="font-medium mt-0.5">{selected.product}</div></div>
                <div><span className="text-xs text-gray-500">수량</span><div className="font-medium mt-0.5">{selected.qty} {selected.unit}</div></div>
                <div><span className="text-xs text-gray-500">공정</span><div className="mt-0.5">{selected.process}</div></div>
                <div><span className="text-xs text-gray-500">담당자</span><div className="mt-0.5">{selected.assignee}</div></div>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs text-gray-600">상태 변경</label>
                <div className="flex gap-2">
                  {(["대기", "진행", "완료"] as Status[]).map(s => (
                    <button
                      key={s}
                      onClick={() => setNewStatus(s)}
                      className={`flex-1 py-2 rounded text-xs font-medium border ${newStatus === s ? "bg-blue-600 text-white border-blue-600" : "text-gray-600 border-gray-200 hover:bg-gray-50"}`}
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setSelected(null)}>취소</Button>
            <Button onClick={saveStatus}>저장</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
